version: 2
jobs:
  build:
    docker:
      - image: circleci/python:3.6
    steps:
      - checkout
      # Download and cache dependencies
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "requirements.txt" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-
      - run:
          name: install tox
          command: |
            python3 -m venv venv
            . venv/bin/activate
            pip install tox
      - save_cache:
          paths:
            - ./venv
          key: v1-dependencies-{{ checksum "requirements.txt" }}
      - run: mkdir nosetests
      - run:
          name: run tests
          command: |
            . venv/bin/activate
            tox -e py36
      - run: cp nosetests.xml nosetests/nosetests.xml
      - run:
          name: run flake8
          command: |
            . venv/bin/activate
            tox -e flake8
      - run:
          name: check coverage
          command: |
            . venv/bin/activate
            tox -e report
      - run:
          name: upload to codacy
          command: |
            . venv/bin/activate
            tox -e xml
            tox -e codacy
      - store_test_results:
          path: nosetests
      - store_artifacts:
          path: flake8.txt
